environment:
  P: "c:/projects/libs"

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\openmeeg

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\openmeeg
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P% -DBUILD_SHARED:BOOL=ON -DBUILD_DOCUMENTATION:BOOL=OFF -DBUILD_TESTING:BOOL=ON -DENABLE_PYTHON:BOOL=OFF -DENABLE_PACKAGING:BOOL=OFF -DUSE_VTK:BOOL=OFF -DUSE_ATLAS:BOOL=OFF -DUSE_SYSTEM_matio:BOOL=OFF -DUSE_SYSTEM_hdf5:BOOL=OFF -DUSE_SYSTEM_zlib:BOOL=OFF -DCMAKE_SKIP_RPATH:BOOL=OFF .
  - cmake --build . --config Release

# scripts to run after build
after_build:
  - cd %P%
  - 7z a c:\projects\openmeeg\openmeeg.zip *.exe -tzip
  - cd c:\projects\openmeeg

artifacts:
  - path: openmeeg.zip
    name: openmeeg.zip

deploy_script:
  - cd c:\projects\openmeeg
