# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

# clone directory
clone_folder: c:\projects\openmeeg

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: build/INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - mkdir C:\projects\openmeeg\build
  - cd C:\projects\openmeeg\build
  - cmake -G "Visual Studio 14 2015 Win64" -DBUILD_SHARED=ON -DBUILD_DOCUMENTATION=OFF -DBUILD_TESTING:BOOL=ON -DENABLE_PYTHON=OFF -DENABLE_PACKAGING:BOOL=ON -DUSE_VTK=OFF -DUSE_ATLAS=OFF -DUSE_SYSTEM_matio:BOOL=OFF -DUSE_SYSTEM_hdf5:BOOL=OFF -DUSE_SYSTEM_zlib=OFF -DCMAKE_SKIP_RPATH:BOOL=OFF -DUSE_LAPACK=ON ..
  - cmake --build . --config Release
  - cpack
  - cpack -G TGZ

# scripts to run after build
after_build:
  - move c:\projects\openmeeg\build\OpenMEEG-2.3.0.1-x64--static.exe .
  - move c:\projects\openmeeg\build\OpenMEEG-2.3.0.1-x64--static.tar.gz .

before_test:
  - echo Running tests...
  - cd C:\projects\openmeeg\OpenMEEG\build
  - ctest -V

artifacts:
  - path: OpenMEEG-*-x64--static.exe
    name: OpenMEEG-x64.exe
  - path: OpenMEEG-*-x64--static.tar.gz
    name: OpenMEEG-x64.exe    
